baseURL: "https://ngyingzhong.com"
languageCode: "en-us"
title: "Ng Ying Zhong"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"

taxonomies:
  author: authors
